name: quiver_time
version: 1.0.0-dev.1
authors:
- Justin Fagnani <justinfagnani@google.com>
- Yegor Jbanov <yjbanov@google.com>
- Chris Bracken <cbracken@google.com>
- Alexandre Ardhuin <alexandre.ardhuin@gmail.com>
- David Morgan <davidmorgan@google.com>
- John McDole <codefu@google.com>
- Matan Lurey <matanl@google.com>
- Günter Zöchbauer <guenter@gzoechbauer.com>
- Sean Eagan <seaneagan1@gmail.com>
- Victor Berchet <victor@suumit.com>
description: Utilities for working with time
homepage: https://github.com/QuiverDart/quiver_time
environment:
  sdk: '>=1.8.0 <2.0.0'
dev_dependencies:
  test: '>=0.12.0 <0.13.0'
